version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000" # Proxy Port
      - "9901:9901"   # Admin Port
    depends_on:
      - python_backend
    networks:
      - app_network

  python_backend:
    build: ./python-server # Path to Python Dockerfile
    networks:
      - app_network

  react_frontend:
    build: ./react-app # Path to React Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
